### ISSUE TITLE
How to get it running locally?

### ISSUE THREAD

**Issue by justanotherdev123** [jerryzlau/OpenRice#53]
Hi,

I was wondering if we could get a read me on how to get this running locally and how to deploy to heroku?

Thank you very much. Looking forward to learning from this :)

**Comment by jerryzlau** [comment]
After you clone the repo: 
1. Run webpack -w
2. Run rails s 
3. the website should be running locally on port 3000

**Comment by ckim2013** [comment]
Step 0: npm install

**Comment by justanotherdev123** [comment]
Thank you very much!

Also do you have a guide on how to deploy to Heroku and are you following a guide somewhere to build this? :)

**Comment by jerryzlau** [comment]
If you create an account on heroku and create app on their platform, they give you instructions on how to deploy

**Comment by justanotherdev123** [comment]
And are you following some online course to build this app out?

**Comment by jerryzlau** [comment]
No I went to a bootcamp, they taught us the basics and we built it

**Comment by justanotherdev123** [comment]
Last question, sorry to bother what version of ruby do i need installed for this?

**Comment by jerryzlau** [comment]
No worries, you can use the latest version of ruby.

**Comment by justanotherdev123** [comment]
Do I need to set up a DB?  How can I do this? Thought the app would create it.

![screenshot 2017-11-04 21 01 10](https://user-images.githubusercontent.com/17953794/32409412-4d46328c-c1a3-11e7-8455-b03310895d83.png)

**Comment by jerryzlau** [comment]
yea you need to run postgresql and you have to do migration

**Comment by justanotherdev123** [comment]
How do I do the migration?

P.S. Just looking at your code Im actually learning quite a bit. I'm learning Rails right now. :)
